// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	job "recon-service/internal/domain/job"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0
func (_m *Repository) Create(_a0 *job.Job) {
	_m.Called(_a0)
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 *job.Job
func (_e *Repository_Expecter) Create(_a0 interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *Repository_Create_Call) Run(run func(_a0 *job.Job)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*job.Job))
	})
	return _c
}

func (_c *Repository_Create_Call) Return() *Repository_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(*job.Job)) *Repository_Create_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *Repository) Get(id string) (*job.Job, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *job.Job
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*job.Job, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *job.Job); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*job.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Repository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Repository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *Repository_Expecter) Get(id interface{}) *Repository_Get_Call {
	return &Repository_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *Repository_Get_Call) Run(run func(id string)) *Repository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_Get_Call) Return(_a0 *job.Job, _a1 bool) *Repository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Get_Call) RunAndReturn(run func(string) (*job.Job, bool)) *Repository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0
func (_m *Repository) Update(_a0 *job.Job) {
	_m.Called(_a0)
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 *job.Job
func (_e *Repository_Expecter) Update(_a0 interface{}) *Repository_Update_Call {
	return &Repository_Update_Call{Call: _e.mock.On("Update", _a0)}
}

func (_c *Repository_Update_Call) Run(run func(_a0 *job.Job)) *Repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*job.Job))
	})
	return _c
}

func (_c *Repository_Update_Call) Return() *Repository_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *Repository_Update_Call) RunAndReturn(run func(*job.Job)) *Repository_Update_Call {
	_c.Run(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
