// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	job "recon-service/internal/domain/job"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with no fields
func (_m *Service) Create() (*job.Job, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *job.Job
	var r1 error
	if rf, ok := ret.Get(0).(func() (*job.Job, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *job.Job); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*job.Job)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Service_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
func (_e *Service_Expecter) Create() *Service_Create_Call {
	return &Service_Create_Call{Call: _e.mock.On("Create")}
}

func (_c *Service_Create_Call) Run(run func()) *Service_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Create_Call) Return(_a0 *job.Job, _a1 error) *Service_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Create_Call) RunAndReturn(run func() (*job.Job, error)) *Service_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithKey provides a mock function with given fields: idempotencyKey
func (_m *Service) CreateWithKey(idempotencyKey string) (*job.Job, bool) {
	ret := _m.Called(idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithKey")
	}

	var r0 *job.Job
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*job.Job, bool)); ok {
		return rf(idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(string) *job.Job); ok {
		r0 = rf(idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*job.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(idempotencyKey)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Service_CreateWithKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithKey'
type Service_CreateWithKey_Call struct {
	*mock.Call
}

// CreateWithKey is a helper method to define mock.On call
//   - idempotencyKey string
func (_e *Service_Expecter) CreateWithKey(idempotencyKey interface{}) *Service_CreateWithKey_Call {
	return &Service_CreateWithKey_Call{Call: _e.mock.On("CreateWithKey", idempotencyKey)}
}

func (_c *Service_CreateWithKey_Call) Run(run func(idempotencyKey string)) *Service_CreateWithKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Service_CreateWithKey_Call) Return(res *job.Job, existJob bool) *Service_CreateWithKey_Call {
	_c.Call.Return(res, existJob)
	return _c
}

func (_c *Service_CreateWithKey_Call) RunAndReturn(run func(string) (*job.Job, bool)) *Service_CreateWithKey_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *Service) Get(id string) (*job.Job, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *job.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*job.Job, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *job.Job); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*job.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Service_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *Service_Expecter) Get(id interface{}) *Service_Get_Call {
	return &Service_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *Service_Get_Call) Run(run func(id string)) *Service_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Service_Get_Call) Return(_a0 *job.Job, _a1 error) *Service_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Get_Call) RunAndReturn(run func(string) (*job.Job, error)) *Service_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
