// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	reconcile "recon-service/internal/domain/reconcile"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: system, banks
func (_m *Service) Execute(system []reconcile.SystemTransaction, banks []reconcile.BankTransaction) (reconcile.Summary, error) {
	ret := _m.Called(system, banks)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 reconcile.Summary
	var r1 error
	if rf, ok := ret.Get(0).(func([]reconcile.SystemTransaction, []reconcile.BankTransaction) (reconcile.Summary, error)); ok {
		return rf(system, banks)
	}
	if rf, ok := ret.Get(0).(func([]reconcile.SystemTransaction, []reconcile.BankTransaction) reconcile.Summary); ok {
		r0 = rf(system, banks)
	} else {
		r0 = ret.Get(0).(reconcile.Summary)
	}

	if rf, ok := ret.Get(1).(func([]reconcile.SystemTransaction, []reconcile.BankTransaction) error); ok {
		r1 = rf(system, banks)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Service_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - system []reconcile.SystemTransaction
//   - banks []reconcile.BankTransaction
func (_e *Service_Expecter) Execute(system interface{}, banks interface{}) *Service_Execute_Call {
	return &Service_Execute_Call{Call: _e.mock.On("Execute", system, banks)}
}

func (_c *Service_Execute_Call) Run(run func(system []reconcile.SystemTransaction, banks []reconcile.BankTransaction)) *Service_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]reconcile.SystemTransaction), args[1].([]reconcile.BankTransaction))
	})
	return _c
}

func (_c *Service_Execute_Call) Return(_a0 reconcile.Summary, _a1 error) *Service_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Execute_Call) RunAndReturn(run func([]reconcile.SystemTransaction, []reconcile.BankTransaction) (reconcile.Summary, error)) *Service_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
